pipeline:
  name: test-snuba
  identifier: testsnuba
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: snuba
        build: <+input>
  stages:
    - stage:
        name: snuba-arm64-image-not-arm
        identifier: snubaarm64imagenotarm
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: log arc
                  identifier: log_arc
                  spec:
                    shell: Sh
                    command: |
                      cat /proc/cpuinfo

                      lscpu

                      uname -m
              - step:
                  type: Run
                  name: Create Image
                  identifier: Create_Image
                  spec:
                    shell: Sh
                    command: |-
                      docker buildx create --name arm64-builder --use
                      docker buildx build --platform linux/arm64 \
                      --build-arg BUILDKIT_INLINE_CACHE=1 \
                      -t <+pipeline.variables.SNUBA_IMAGE>:latest \
                      -t <+pipeline.variables.SNUBA_IMAGE>:${{ steps.branch.outputs.branch }} \
                      -t <+pipeline.variables.SNUBA_IMAGE>:${{ github.sha }} \
                      --load .
        variables:
          - name: SNUBA_IMAGE
            type: String
            description: ""
            value: ghcr.io/getsentry/snuba-arm64-dev
