pipeline:
  name: test-snuba
  identifier: testsnuba
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: snuba
        build: <+input>
  stages:
    - stage:
        name: snuba-arm64-image-not-arm
        identifier: snubaarm64imagenotarm
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: log arc
                  identifier: log_arc
                  spec:
                    shell: Sh
                    command: cat /proc/cpuinfo
        variables:
          - name: SNUBA_IMAGE
            type: String
            description: ""
            value: ghcr.io/getsentry/snuba-arm64-dev
